---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_docker_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for the docker service
  - n=0; while [ "$n" -lt 60 ] && [ ! "$(docker stats --no-stream)" ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t quay.io/ukhomeofficedigital/etcd-backup:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push
    - tag

- name: scan
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission
  environment:
    DOCKERFILE: Dockerfile
    FAIL_ON_DETECTION: true
    IMAGE_NAME: quay.io/ukhomeofficedigital/etcd-backup:${DRONE_COMMIT_SHA}
    TOLERATES: medium
  when:
    event:
    - push

- name: image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="ukhomeofficedigital+drone_docker_etcdbackup" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/etcd-backup:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/etcd-backup:latest
  - docker push quay.io/ukhomeofficedigital/etcd-backup:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/etcd-backup:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

- name: tagged_image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="ukhomeofficedigital+drone_docker_etcdbackup" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/etcd-backup:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/etcd-backup:$${DRONE_TAG}
  - docker push quay.io/ukhomeofficedigital/etcd-backup:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission
  commands:
  - /run.sh server
  when:
    event:
    - push
...
